//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Movie12Entities : DbContext
    {
        public Movie12Entities()
            : base("name=Movie12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cast> Casts { get; set; }
        public virtual DbSet<Cast_Movie> Cast_Movie { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CTTapPhim> CTTapPhims { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MyList> MyLists { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<PhimBo> PhimBoes { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Cast_TVSeries> Cast_TVSeries { get; set; }
    }
}
