//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public string ID { get; set; }
        public string Email { get; set; }
        public string NamePrice { get; set; }
        public Nullable<System.DateTime> Datedinscription { get; set; }
        public Nullable<System.DateTime> Datedexpiration { get; set; }
    }
}
